### ISSUE TITLE
Integrate Hostname change on Playbook

### ISSUE THREAD

**Issue by guiadco** [TheFkinCompany/allspark#12] opened 2018-06-11 10:56 UTC
Seems to have a problem on the hostname or it's network contention on segregate network.

Need to see later.

**Comment by guiadco** [comment] 2018-06-11 12:36
Seems to have a problem on the hostname or it's network contention on segregate network.

Need to see later.

**Comment by Xide** [comment] 2018-06-15 13:18
Could not reproduce. Closing issue.

**Closed by Xide** 2018-06-15 13:18 UTC
Labels: invalid, need_infos
