### ISSUE TITLE
Error on Docker start

### ISSUE THREAD

**Issue by guiadco** [TheFkinCompany/allspark#16] opened 2018-06-18 10:33 UTC
```
TASK [system : Start Docker service] ************************************************************************************************************************
********************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}
        to retry, use: --limit @/home/artifactory/install.retry

When you have a different version of our docker, the ansible docker role does not start docker automatically.
```

Test to reproduce the problem:
-> ansible playbook with centos up-to-date

**Comment by guiadco** [comment] 2018-06-21 17:17
When you have the system up-to-date with the last kernel on CentOS 7.5, i can't use the playbook, i need to modify the group_vars to choose the 18.03 version of docker.
I need to see what is the kernel version of the vagrant box to compare.

**Comment by guiadco** [comment] 2018-06-21 17:20
It's will be necessary to be carefulness the system layer :)

**Comment by Xide** [comment] 2018-07-01 15:28
Can't reproduce using the master vagrant box with an up to date 'centos/7'. Closing this issue, feel free to reopen if you can find a way to reproduce this.

**Closed by Xide** 2018-07-01 15:28 UTC
Labels: bug, need_infos
